name: ${project.name}
main: ${project.groupId}.simplecoloredmotd.${project.name}
version: ${project.version}
description: ${project.description}
 
commands:
    motd:
        aliases: [m]
        usage: /<command>
        description: View MOTD
    setmotd:
        aliases: [sm, setm, smotd]
        usage: /<command>
        description: Set MOTD
    setservermotd:
        aliases: [ssm, setsm, ssmotd]
        usage: /<command>
        description: Set system MOTD
       
permissions:
    motd.*:
       description: Use all MOTD commands
       children:
           motd.check: true
           motd.set: true
       default: op
    motd.check:
        description: Check the MOTD.
        default: true
    motd.set:
        description: Use the setmotd command to change the MOTD
        default: op